-- AlterTable
ALTER TABLE "User" ALTER COLUMN "U_Cidade" DROP NOT NULL,
ALTER COLUMN "U_DirectReports" DROP NOT NULL,
ALTER COLUMN "U_EmployeeNumber" DROP NOT NULL,
ALTER COLUMN "U_Foto" DROP NOT NULL,
ALTER COLUMN "U_Name" DROP NOT NULL,
ALTER COLUMN "U_Pais" DROP NOT NULL,
ALTER COLUMN "U_Role" DROP NOT NULL,
ALTER COLUMN "U_Seniority" DROP NOT NULL,
ALTER COLUMN "U_StartingDate" DROP NOT NULL,
ALTER COLUMN "U_Type" DROP NOT NULL,
ALTER COLUMN "U_group" DROP NOT NULL,
ALTER COLUMN "U_permission" DROP NOT NULL,
ALTER COLUMN "U_permission" SET DATA TYPE TEXT;
